version: "3.6"

services:
  backend:
    container_name: ${PROJECT_NAME}_backend
    image: openizr/node:3.0.0-dev
    env_file:
      - .env
    ports:
      - "${HOST_IP}:${BACKEND_PORT}:${BACKEND_PORT}"
    command: sh -c "yarn && yarn run dev"
    volumes:
      - ./backend:/var/www/html
    restart: unless-stopped
  frontend:
    container_name: ${PROJECT_NAME}_frontend
    image: openizr/node:3.0.0-dev
    env_file:
      - .env
    ports:
      - "${HOST_IP}:${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: sh -c "yarn && yarn run dev"
    volumes:
      - ./frontend:/var/www/html
    restart: unless-stopped

# For people that use a VPN
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
